// languages.js

const translations = {
    "en": {
        "app_title": "Cat Guardians - Home of Love and Hope",
        "home_title": "Welcome to Cat Guardians Home",
        "home_subtitle": "Join us to create a better world for stray cats.",
        "nav_our_story": "Our Story",
        "nav_cat_cafe_alliance": "Cat Cafe Alliance",
        "nav_donate": "Donate",
        "nav_tracking": "Tracking",
        "section_our_story_title": "Our Story",
        "story_para1": "Hello! I'm Aiko, an ordinary cat lover. My story began with a little cat named 'Peanut'. Three years ago, on a cold rainy night, I found Peanut huddled in a corner, completely drenched. She was emaciated and her eyes were full of fear. At that moment, I decided to take her home and give her a warm sanctuary.",
        "story_para2": "After recovering, Peanut became lively and adorable, returning my love in her own unique way every day. Her arrival completely changed my life and made me realize that countless stray cats, just like Peanut, needed help. This strong sense of mission drove me to create this platform, hoping to gather more love and support for these homeless little lives.",
        "story_para3": "We believe every life deserves to be treated with kindness. Through this website, we hope to share our story, connect with more like-minded friends, and together provide food, medical care, and homes for stray cats. Thank you for visiting, we look forward to shining a light of hope for cats with you!",
        "section_cat_cafe_alliance_title": "Cat Cafe Alliance",
        "cafe_odd_cat_title": "Odd Cat Cafe Bali",
        "cafe_odd_cat_address": "Address: Jl. Raya Canggu No.88, Canggu, Bali, Indonesia",
        "cafe_paws_cat_title": "Paws Cat Cafe Thailand",
        "cafe_paws_cat_address": "Address: 123 Sukhumvit Rd, Bangkok, Thailand",
        "cafe_details_odd_cat_title": "Cats at Odd Cat Cafe Bali",
        "cat_peanut_name": "Cat: Peanut",
        "cat_peanut_char": "Personality: Lively and playful, loves playing with feather wands.",
        "cat_sugar_bean_name": "Cat: Sugar Bean",
        "cat_sugar_bean_char": "Personality: Gentle and affectionate, loves being petted.",
        "cafe_details_paws_cat_title": "Cats at Paws Cat Cafe Thailand",
        "cat_coffee_name": "Cat: Coffee",
        "cat_coffee_char": "Personality: Aloof and proud, but gentle at heart.",
        "cat_milk_name": "Cat: Milk",
        "cat_milk_char": "Personality: Curious and loves exploring new things.",
        "back_to_cafes_btn": "Back to Cafes List",
        "section_donate_title": "Donate to Support",
        "donate_subtitle": "Every bit of your kindness will bring warmth and hope to stray cats.",
        "donate_method_alipay": "Alipay",
        "donate_method_credit_card": "Credit Card (Visa/Mastercard)",
        "donate_method_apple_pay": "Apple Pay",
        "donate_method_paypal": "PayPal",
        "donate_form_title": "Fill in Donation Information",
        "donate_label_name": "Donor Name (or Nickname):",
        "donate_label_location": "Location:",
        "donate_label_amount": "Donation Amount (RMB):",
        "donate_submit_btn": "Confirm Donation",
        "donate_recent_donations": "Recent Donation Records",
        "donate_alert_success": "Thank you for your donation! Your kindness will help more cats.",
        "donate_alert_invalid": "Please fill in all donation information and ensure the amount is greater than 0.",
        "section_tracking_title": "Expense Tracking",
        "tracking_subtitle": "The whereabouts of every donation will be transparently disclosed.",
        "tracking_header_date": "Expense Date",
        "tracking_header_category": "Category",
        "tracking_header_proof": "Payment Proof",
        "tracking_header_payer": "Payer",
        "tracking_proof_view": "View Proof",
        "tracking_proof_none": "No Proof",
        "tracking_add_expense_btn": "Add New Expense",
        "tracking_modal_title": "Add New Expense Record",
        "tracking_label_date": "Expense Date:",
        "tracking_label_category": "Category:",
        "tracking_label_proof": "Payment Proof (Image Upload):",
        "tracking_proof_note": "Please upload a proof image.",
        "tracking_label_payer": "Payer:",
        "tracking_submit_btn": "Submit",
        "tracking_alert_upload_note": "Note: Image proof is for local preview only in this example. For a real website, you'll need to upload files to a server and get an accessible link.",
        "tracking_alert_success": "Expense record added!",
        "footer_text": "© 2024 Cat Guardians. All rights reserved.",
        "expense_cat_food": "Cat Food Purchase",
        "expense_cat_vaccine": "Vaccine Fees",
        "payer_aiko": "Aiko",
        "payer_volunteer_a": "Volunteer A"
    },
    "zh": {
        "app_title": "猫咪守护者 - 爱与希望的家园",
        "home_title": "欢迎来到猫咪守护者之家",
        "home_subtitle": "与我们一同，为流浪猫咪创造一个更美好的世界。",
        "nav_our_story": "我们的故事",
        "nav_cat_cafe_alliance": "猫咖联盟",
        "nav_donate": "捐款",
        "nav_tracking": "追踪",
        "section_our_story_title": "我们的故事",
        "story_para1": "你好！我叫小爱，一个平凡的猫咪爱好者。我的故事，始于一只名叫“花生”的小猫。那是三年前一个寒冷的雨夜，我在回家的路上发现了蜷缩在角落里，浑身湿透的花生。它瘦弱不堪，眼神中充满了恐惧。那一刻，我决定带它回家，给它一个温暖的港湾。",
        "story_para2": "花生康复后，变得活泼可爱，每天都用它独特的方式回报着我的爱。它的到来，彻底改变了我的生活，也让我意识到，还有无数像花生一样需要帮助的流浪猫咪。这份强烈的使命感驱使我建立了这个平台，希望能汇聚更多爱心，为这些无家可归的小生命提供帮助。",
        "story_para3": "我们相信，每一个生命都值得被温柔以待。通过这个网站，我们希望分享我们的故事，连接更多志同道合的朋友，一起为流浪猫咪提供食物、医疗和家园。感谢你的到访，期待与你一同为猫咪们点亮希望！",
        "section_cat_cafe_alliance_title": "猫咖联盟",
        "cafe_odd_cat_title": "巴厘岛 Odd Cat Cafe",
        "cafe_odd_cat_address": "地址：Jl. Raya Canggu No.88, Canggu, Bali, Indonesia",
        "cafe_paws_cat_title": "泰国 Paws Cat Cafe",
        "cafe_paws_cat_address": "地址：123 Sukhumvit Rd, Bangkok, Thailand",
        "cafe_details_odd_cat_title": "巴厘岛 Odd Cat Cafe 的猫咪",
        "cat_peanut_name": "喵星人：花生",
        "cat_peanut_char": "性格：活泼好动，喜欢玩逗猫棒。",
        "cat_sugar_bean_name": "喵星人：糖豆",
        "cat_sugar_bean_char": "性格：温顺粘人，喜欢被人抚摸。",
        "cafe_details_paws_cat_title": "泰国 Paws Cat Cafe 的猫咪",
        "cat_coffee_name": "喵星人：咖啡",
        "cat_coffee_char": "性格：高冷傲娇，但内心温柔。",
        "cat_milk_name": "喵星人：牛奶",
        "cat_milk_char": "性格：好奇心强，喜欢探索新事物。",
        "back_to_cafes_btn": "返回猫咖列表",
        "section_donate_title": "捐款支持",
        "donate_subtitle": "你的每一份心意，都将为流浪猫咪带去温暖与希望。",
        "donate_method_alipay": "支付宝",
        "donate_method_credit_card": "信用卡 (Visa/Mastercard)",
        "donate_method_apple_pay": "苹果支付",
        "donate_method_paypal": "PayPal",
        "donate_form_title": "填写捐款信息",
        "donate_label_name": "捐款人姓名 (或昵称):",
        "donate_label_location": "地点:",
        "donate_label_amount": "捐款金额 (RMB):",
        "donate_submit_btn": "确认捐款",
        "donate_recent_donations": "近期捐款记录",
        "donate_alert_success": "感谢您的捐款！您的爱心将帮助更多猫咪。",
        "donate_alert_invalid": "请填写所有捐款信息，并确保金额大于0。",
        "section_tracking_title": "支出追踪",
        "tracking_subtitle": "每一笔善款的去向都将透明公开。",
        "tracking_header_date": "支出日期",
        "tracking_header_category": "类目",
        "tracking_header_proof": "付款凭证",
        "tracking_header_payer": "付款人",
        "tracking_proof_view": "查看凭证",
        "tracking_proof_none": "无凭证",
        "tracking_add_expense_btn": "添加新支出",
        "tracking_modal_title": "添加新的支出记录",
        "tracking_label_date": "支出日期:",
        "tracking_label_category": "类目:",
        "tracking_label_proof": "付款凭证 (图片上传):",
        "tracking_proof_note": "请上传凭证图片。",
        "tracking_label_payer": "付款人:",
        "tracking_submit_btn": "提交",
        "tracking_alert_upload_note": "注意：图片凭证在此示例中仅为本地预览。在实际网站中，您需要将文件上传到服务器并获取可访问的链接。",
        "tracking_alert_success": "支出记录已添加！",
        "footer_text": "© 2024 猫咪守护者. 版权所有。",
        "expense_cat_food": "猫粮采购",
        "expense_cat_vaccine": "疫苗费用",
        "payer_aiko": "小爱",
        "payer_volunteer_a": "志愿者A"
    },
    "ko": {
        "app_title": "고양이 수호자 - 사랑과 희망의 보금자리",
        "home_title": "고양이 수호자 집에 오신 것을 환영합니다",
        "home_subtitle": "저희와 함께 길고양이를 위한 더 나은 세상을 만들어 보세요.",
        "nav_our_story": "우리의 이야기",
        "nav_cat_cafe_alliance": "고양이 카페 연합",
        "nav_donate": "기부",
        "nav_tracking": "추적",
        "section_our_story_title": "우리의 이야기",
        "story_para1": "안녕하세요! 저는 평범한 고양이 애호가 아이코입니다. 저의 이야기는 '피넛'이라는 작은 고양이와 함께 시작되었습니다. 3년 전 추운 비 오는 밤, 저는 길에서 웅크리고 앉아 비에 흠뻑 젖은 피넛을 발견했습니다. 피넛은 야위고 눈에는 두려움이 가득했습니다. 그 순간, 저는 피넛을 집으로 데려와 따뜻한 보금자리를 제공하기로 결심했습니다.",
        "story_para2": "회복 후 피넛은 활기차고 사랑스러워졌고, 매일 자신만의 방식으로 저의 사랑에 보답했습니다. 피넛의 등장은 저의 삶을 완전히 바꾸어 놓았고, 피넛처럼 도움이 필요한 수많은 길고양이들이 있다는 것을 깨닫게 했습니다. 이러한 강한 사명감으로 저는 이 플랫폼을 만들게 되었고, 더 많은 사랑을 모아 이 불쌍한 작은 생명들에게 도움을 주고 싶습니다.",
        "story_para3": "우리는 모든 생명이 친절하게 대우받을 자격이 있다고 믿습니다. 이 웹사이트를 통해 우리는 우리의 이야기를 공유하고, 같은 생각을 가진 더 많은 친구들과 연결하여 길고양이들에게 음식, 의료 서비스 및 보금자리를 제공하고자 합니다. 방문해 주셔서 감사합니다. 여러분과 함께 고양이들에게 희망의 빛을 밝히기를 기대합니다!",
        "section_cat_cafe_alliance_title": "고양이 카페 연합",
        "cafe_odd_cat_title": "발리 오드 캣 카페",
        "cafe_odd_cat_address": "주소: Jl. Raya Canggu No.88, Canggu, Bali, Indonesia",
        "cafe_paws_cat_title": "태국 파우스 캣 카페",
        "cafe_paws_cat_address": "주소: 123 Sukhumvit Rd, Bangkok, Thailand",
        "cafe_details_odd_cat_title": "발리 오드 캣 카페의 고양이들",
        "cat_peanut_name": "고양이: 피넛",
        "cat_peanut_char": "성격: 활기차고 장난기 많으며, 깃털 장난감을 가지고 노는 것을 좋아합니다.",
        "cat_sugar_bean_name": "고양이: 슈가빈",
        "cat_sugar_bean_char": "성격: 온순하고 애교 많으며, 쓰다듬는 것을 좋아합니다.",
        "cafe_details_paws_cat_title": "태국 파우스 캣 카페의 고양이들",
        "cat_coffee_name": "고양이: 커피",
        "cat_coffee_char": "성격: 냉정하고 도도하지만, 속마음은 다정합니다.",
        "cat_milk_name": "고양이: 밀크",
        "cat_milk_char": "성격: 호기심이 많고 새로운 것을 탐험하는 것을 좋아합니다.",
        "back_to_cafes_btn": "카페 목록으로 돌아가기",
        "section_donate_title": "기부 지원",
        "donate_subtitle": "여러분의 작은 마음 하나하나가 길고양이들에게 따뜻함과 희망을 가져다줄 것입니다.",
        "donate_method_alipay": "알리페이",
        "donate_method_credit_card": "신용카드 (비자/마스터카드)",
        "donate_method_apple_pay": "애플 페이",
        "donate_method_paypal": "페이팔",
        "donate_form_title": "기부 정보 입력",
        "donate_label_name": "기부자 이름 (또는 닉네임):",
        "donate_label_location": "위치:",
        "donate_label_amount": "기부 금액 (RMB):",
        "donate_submit_btn": "기부 확인",
        "donate_recent_donations": "최근 기부 기록",
        "donate_alert_success": "기부에 감사드립니다! 여러분의 사랑이 더 많은 고양이들에게 도움이 될 것입니다.",
        "donate_alert_invalid": "모든 기부 정보를 입력하고 금액이 0보다 큰지 확인해 주세요.",
        "section_tracking_title": "지출 추적",
        "tracking_subtitle": "모든 기부금의 사용 내역은 투명하게 공개됩니다.",
        "tracking_header_date": "지출 날짜",
        "tracking_header_category": "카테고리",
        "tracking_header_proof": "결제 증명",
        "tracking_header_payer": "결제자",
        "tracking_proof_view": "증명 보기",
        "tracking_proof_none": "증명 없음",
        "tracking_add_expense_btn": "새 지출 추가",
        "tracking_modal_title": "새 지출 기록 추가",
        "tracking_label_date": "지출 날짜:",
        "tracking_label_category": "카테고리:",
        "tracking_label_proof": "결제 증명 (이미지 업로드):",
        "tracking_proof_note": "증명 이미지를 업로드해 주세요.",
        "tracking_label_payer": "결제자:",
        "tracking_submit_btn": "제출",
        "tracking_alert_upload_note": "참고: 이미지 증명은 이 예시에서만 로컬 미리보기용입니다. 실제 웹사이트에서는 파일을 서버에 업로드하고 접근 가능한 링크를 얻어야 합니다.",
        "tracking_alert_success": "지출 기록이 추가되었습니다!",
        "footer_text": "© 2024 고양이 수호자. 모든 권리 보유.",
        "expense_cat_food": "고양이 사료 구매",
        "expense_cat_vaccine": "백신 비용",
        "payer_aiko": "아이코",
        "payer_volunteer_a": "자원봉사자 A"
    },
    "id": {
        "app_title": "Penjaga Kucing - Rumah Penuh Cinta dan Harapan",
        "home_title": "Selamat Datang di Rumah Penjaga Kucing",
        "home_subtitle": "Bergabunglah bersama kami untuk menciptakan dunia yang lebih baik bagi kucing jalanan.",
        "nav_our_story": "Kisah Kami",
        "nav_cat_cafe_alliance": "Aliansi Kafe Kucing",
        "nav_donate": "Donasi",
        "nav_tracking": "Pelacakan",
        "section_our_story_title": "Kisah Kami",
        "story_para1": "Halo! Saya Aiko, seorang pecinta kucing biasa. Kisah saya dimulai dengan seekor kucing kecil bernama 'Peanut'. Tiga tahun lalu, pada malam yang dingin dan hujan, saya menemukan Peanut meringkuk di sudut, basah kuyup. Dia sangat kurus dan matanya penuh ketakutan. Saat itu, saya memutuskan untuk membawanya pulang dan memberinya tempat yang hangat.",
        "story_para2": "Setelah pulih, Peanut menjadi lincah dan menggemaskan, membalas cinta saya dengan caranya sendiri setiap hari. Kedatangannya benar-benar mengubah hidup saya dan menyadarkan saya bahwa ada banyak kucing jalanan seperti Peanut yang membutuhkan bantuan. Rasa misi yang kuat ini mendorong saya untuk membuat platform ini, berharap dapat mengumpulkan lebih banyak kasih sayang dan dukungan untuk makhluk kecil yang tidak punya rumah ini.",
        "story_para3": "Kami percaya setiap kehidupan layak diperlakukan dengan baik. Melalui situs web ini, kami berharap dapat berbagi kisah kami, terhubung dengan lebih banyak teman yang sepikiran, dan bersama-sama menyediakan makanan, perawatan medis, dan rumah bagi kucing jalanan. Terima kasih telah berkunjung, kami berharap dapat menyalakan cahaya harapan bagi kucing bersama Anda!",
        "section_cat_cafe_alliance_title": "Aliansi Kafe Kucing",
        "cafe_odd_cat_title": "Odd Cat Cafe Bali",
        "cafe_odd_cat_address": "Alamat: Jl. Raya Canggu No.88, Canggu, Bali, Indonesia",
        "cafe_paws_cat_title": "Paws Cat Cafe Thailand",
        "cafe_paws_cat_address": "Alamat: 123 Sukhumvit Rd, Bangkok, Thailand",
        "cafe_details_odd_cat_title": "Kucing di Odd Cat Cafe Bali",
        "cat_peanut_name": "Kucing: Peanut",
        "cat_peanut_char": "Kepribadian: Lincah dan suka bermain, suka bermain dengan tongkat bulu.",
        "cat_sugar_bean_name": "Kucing: Sugar Bean",
        "cat_sugar_bean_char": "Kepribadian: Lembut dan manja, suka dielus.",
        "cafe_details_paws_cat_title": "Kucing di Paws Cat Cafe Thailand",
        "cat_coffee_name": "Kucing: Coffee",
        "cat_coffee_char": "Kepribadian: Dingin dan bangga, tetapi berhati lembut.",
        "cat_milk_name": "Kucing: Milk",
        "cat_milk_char": "Kepribadian: Penasaran dan suka menjelajahi hal-hal baru.",
        "back_to_cafes_btn": "Kembali ke Daftar Kafe",
        "section_donate_title": "Donasi untuk Mendukung",
        "donate_subtitle": "Setiap kebaikan Anda akan membawa kehangatan dan harapan bagi kucing jalanan.",
        "donate_method_alipay": "Alipay",
        "donate_method_credit_card": "Kartu Kredit (Visa/Mastercard)",
        "donate_method_apple_pay": "Apple Pay",
        "donate_method_paypal": "PayPal",
        "donate_form_title": "Isi Informasi Donasi",
        "donate_label_name": "Nama Donatur (atau Panggilan):",
        "donate_label_location": "Lokasi:",
        "donate_label_amount": "Jumlah Donasi (RMB):",
        "donate_submit_btn": "Konfirmasi Donasi",
        "donate_recent_donations": "Catatan Donasi Terbaru",
        "donate_alert_success": "Terima kasih atas donasi Anda! Kebaikan Anda akan membantu lebih banyak kucing.",
        "donate_alert_invalid": "Harap isi semua informasi donasi dan pastikan jumlahnya lebih besar dari 0.",
        "section_tracking_title": "Pelacakan Pengeluaran",
        "tracking_subtitle": "Setiap donasi akan diungkapkan secara transparan.",
        "tracking_header_date": "Tanggal Pengeluaran",
        "tracking_header_category": "Kategori",
        "tracking_header_proof": "Bukti Pembayaran",
        "tracking_header_payer": "Pembayar",
        "tracking_proof_view": "Lihat Bukti",
        "tracking_proof_none": "Tidak Ada Bukti",
        "tracking_add_expense_btn": "Tambah Pengeluaran Baru",
        "tracking_modal_title": "Tambah Catatan Pengeluaran Baru",
        "tracking_label_date": "Tanggal Pengeluaran:",
        "tracking_label_category": "Kategori:",
        "tracking_label_proof": "Bukti Pembayaran (Unggah Gambar):",
        "tracking_proof_note": "Harap unggah gambar bukti.",
        "tracking_label_payer": "Pembayar:",
        "tracking_submit_btn": "Kirim",
        "tracking_alert_upload_note": "Catatan: Bukti gambar hanya untuk pratinjau lokal dalam contoh ini. Untuk situs web nyata, Anda perlu mengunggah file ke server dan mendapatkan tautan yang dapat diakses.",
        "tracking_alert_success": "Catatan pengeluaran telah ditambahkan!",
        "footer_text": "© 2024 Penjaga Kucing. Hak Cipta Dilindungi Undang-Undang.",
        "expense_cat_food": "Pembelian Makanan Kucing",
        "expense_cat_vaccine": "Biaya Vaksin",
        "payer_aiko": "Aiko",
        "payer_volunteer_a": "Relawan A"
    },
    "th": {
        "app_title": "ผู้พิทักษ์แมว - บ้านแห่งความรักและความหวัง",
        "home_title": "ยินดีต้อนรับสู่บ้านผู้พิทักษ์แมว",
        "home_subtitle": "มาร่วมสร้างโลกที่ดีขึ้นสำหรับแมวจรจัดไปด้วยกัน",
        "nav_our_story": "เรื่องราวของเรา",
        "nav_cat_cafe_alliance": "พันธมิตรร้านคาเฟ่แมว",
        "nav_donate": "บริจาค",
        "nav_tracking": "ติดตาม",
        "section_our_story_title": "เรื่องราวของเรา",
        "story_para1": "สวัสดีค่ะ! ฉันชื่อไอโกะ เป็นคนรักแมวธรรมดาๆ คนหนึ่ง เรื่องราวของฉันเริ่มต้นขึ้นกับแมวตัวเล็กๆ ชื่อ 'พีนัท' เมื่อสามปีที่แล้ว ในคืนฝนตกหนาวเหน็บ ฉันพบพีนัทซุกตัวอยู่ที่มุมหนึ่ง เปียกปอนไปทั้งตัว มันผอมแห้งและดวงตาเต็มไปด้วยความหวาดกลัว ในขณะนั้น ฉันตัดสินใจพาพีนัทกลับบ้านและมอบที่พักพิงที่อบอุ่นให้มัน",
        "story_para2": "หลังจากฟื้นตัว พีนัทก็กลายเป็นแมวที่ร่าเริงน่ารัก และตอบแทนความรักของฉันด้วยวิธีที่เป็นเอกลักษณ์ของมันทุกวัน การมาถึงของพีนัทได้เปลี่ยนชีวิตของฉันไปอย่างสิ้นเชิง และทำให้ฉันตระหนักว่ายังมีแมวจรจัดอีกนับไม่ถ้วนที่ต้องการความช่วยเหลือเหมือนพีนัท ความรู้สึกที่แข็งแกร่งนี้ผลักดันให้ฉันสร้างแพลตฟอร์มนี้ขึ้นมา ด้วยความหวังที่จะรวบรวมความรักและกำลังใจให้แก่ชีวิตเล็กๆ ที่ไร้บ้านเหล่านี้",
        "story_para3": "เราเชื่อว่าทุกชีวิตสมควรได้รับการดูแลด้วยความเมตตา ผ่านเว็บไซต์นี้ เราหวังที่จะแบ่งปันเรื่องราวของเรา เชื่อมโยงกับเพื่อนๆ ที่มีใจเดียวกัน และร่วมกันจัดหาอาหาร การรักษาพยาบาล และบ้านให้แก่แมวจรจัด ขอบคุณสำหรับการเยี่ยมชม เราหวังว่าจะได้ร่วมจุดประกายความหวังให้แก่แมวกับคุณ!",
        "section_cat_cafe_alliance_title": "พันธมิตรร้านคาเฟ่แมว",
        "cafe_odd_cat_title": "Odd Cat Cafe บาหลี",
        "cafe_odd_cat_address": "ที่อยู่: Jl. Raya Canggu No.88, Canggu, Bali, Indonesia",
        "cafe_paws_cat_title": "Paws Cat Cafe ประเทศไทย",
        "cafe_paws_cat_address": "ที่อยู่: 123 Sukhumvit Rd, Bangkok, Thailand",
        "cafe_details_odd_cat_title": "แมวที่ Odd Cat Cafe บาหลี",
        "cat_peanut_name": "แมว: พีนัท",
        "cat_peanut_char": "นิสัย: ร่าเริง ซุกซน ชอบเล่นไม้ล่อแมว",
        "cat_sugar_bean_name": "แมว: ชูการ์บีน",
        "cat_sugar_bean_char": "นิสัย: อ่อนโยน ขี้อ้อน ชอบให้ลูบหัว",
        "cafe_details_paws_cat_title": "แมวที่ Paws Cat Cafe ประเทศไทย",
        "cat_coffee_name": "แมว: คอฟฟี่",
        "cat_coffee_char": "นิสัย: เย็นชา เย่อหยิ่ง แต่หัวใจอ่อนโยน",
        "cat_milk_name": "แมว: มิลค์",
        "cat_milk_char": "นิสัย: อยากรู้อยากเห็น ชอบสำรวจสิ่งใหม่ๆ",
        "back_to_cafes_btn": "กลับไปที่หน้าร้านคาเฟ่",
        "section_donate_title": "บริจาคเพื่อสนับสนุน",
        "donate_subtitle": "ทุกความตั้งใจของคุณจะนำความอบอุ่นและความหวังมาสู่แมวจรจัด",
        "donate_method_alipay": "อาลีเพย์",
        "donate_method_credit_card": "บัตรเครดิต (Visa/Mastercard)",
        "donate_method_apple_pay": "Apple Pay",
        "donate_method_paypal": "PayPal",
        "donate_form_title": "กรอกข้อมูลการบริจาค",
        "donate_label_name": "ชื่อผู้บริจาค (หรือชื่อเล่น):",
        "donate_label_location": "ที่อยู่:",
        "donate_label_amount": "จำนวนเงินบริจาค (หยวน):",
        "donate_submit_btn": "ยืนยันการบริจาค",
        "donate_recent_donations": "บันทึกการบริจาคล่าสุด",
        "donate_alert_success": "ขอขอบคุณสำหรับการบริจาคของคุณ! ความเมตตาของคุณจะช่วยให้แมวจำนวนมากยิ่งขึ้น",
        "donate_alert_invalid": "โปรดกรอกข้อมูลการบริจาคทั้งหมดและตรวจสอบให้แน่ใจว่าจำนวนเงินมากกว่า 0",
        "section_tracking_title": "ติดตามค่าใช้จ่าย",
        "tracking_subtitle": "ทุกการบริจาคจะถูกเปิดเผยอย่างโปร่งใส",
        "tracking_header_date": "วันที่ใช้จ่าย",
        "tracking_header_category": "หมวดหมู่",
        "tracking_header_proof": "หลักฐานการชำระเงิน",
        "tracking_header_payer": "ผู้จ่ายเงิน",
        "tracking_proof_view": "ดูหลักฐาน",
        "tracking_proof_none": "ไม่มีหลักฐาน",
        "tracking_add_expense_btn": "เพิ่มค่าใช้จ่ายใหม่",
        "tracking_modal_title": "เพิ่มบันทึกค่าใช้จ่ายใหม่",
        "tracking_label_date": "วันที่ใช้จ่าย:",
        "tracking_label_category": "หมวดหมู่:",
        "tracking_label_proof": "หลักฐานการชำระเงิน (อัปโหลดรูปภาพ):",
        "tracking_proof_note": "โปรดอัปโหลดรูปภาพหลักฐาน",
        "tracking_label_payer": "ผู้จ่ายเงิน:",
        "tracking_submit_btn": "ส่ง",
        "tracking_alert_upload_note": "หมายเหตุ: หลักฐานรูปภาพสำหรับตัวอย่างนี้ใช้สำหรับการแสดงตัวอย่างในเครื่องเท่านั้น สำหรับเว็บไซต์จริง คุณจะต้องอัปโหลดไฟล์ไปยังเซิร์ฟเวอร์และรับลิงก์ที่เข้าถึงได้",
        "tracking_alert_success": "เพิ่มบันทึกค่าใช้จ่ายแล้ว!",
        "footer_text": "© 2024 ผู้พิทักษ์แมว สงวนลิขสิทธิ์",
        "expense_cat_food": "การซื้ออาหารแมว",
        "expense_cat_vaccine": "ค่าวัคซีน",
        "payer_aiko": "ไอโกะ",
        "payer_volunteer_a": "อาสาสมัคร A"
    },
    "ja": {
        "app_title": "猫の守護者 - 愛と希望の家",
        "home_title": "猫の守護者の家へようこそ",
        "home_subtitle": "私たちと一緒に、野良猫のためにより良い世界を創造しましょう。",
        "nav_our_story": "私たちの物語",
        "nav_cat_cafe_alliance": "猫カフェ提携",
        "nav_donate": "寄付",
        "nav_tracking": "追跡",
        "section_our_story_title": "私たちの物語",
        "story_para1": "こんにちは！私は普通の猫好き、アイコです。私の物語は「ピーナッツ」という小さな猫から始まりました。3年前の寒い雨の夜、私は帰り道で隅にうずくまり、ずぶ濡れになったピーナッツを見つけました。彼女は痩せ細り、目には恐怖が満ちていました。その瞬間、私は彼女を家に連れて帰り、暖かい安息の場所を与えようと決心しました。",
        "story_para2": "回復後、ピーナッツは活発で愛らしくなり、毎日彼女独自のやり方で私の愛に報いてくれました。彼女の到来は私の人生を完全に変え、ピーナッツのように助けを必要としている野良猫が数えきれないほどいることに気づかせてくれました。この強い使命感が私をこのプラットフォームの設立へと駆り立て、これらのホームレスの小さな命により多くの愛と支援を集めたいと願っています。",
        "story_para3": "私たちは、すべての命が親切に扱われるべきだと信じています。このウェブサイトを通じて、私たちの物語を共有し、志を同じくする友人ともっとつながり、一緒に野良猫に食べ物、医療、そして家を提供したいと思っています。ご訪問ありがとうございます。あなたと一緒に猫たちに希望の光を灯すことを楽しみにしています！",
        "section_cat_cafe_alliance_title": "猫カフェ提携",
        "cafe_odd_cat_title": "バリ Odd Cat Cafe",
        "cafe_odd_cat_address": "住所: Jl. Raya Canggu No.88, Canggu, Bali, Indonesia",
        "cafe_paws_cat_title": "タイ Paws Cat Cafe",
        "cafe_paws_cat_address": "住所: 123 Sukhumvit Rd, Bangkok, Thailand",
        "cafe_details_odd_cat_title": "バリ Odd Cat Cafe の猫たち",
        "cat_peanut_name": "猫: ピーナッツ",
        "cat_peanut_char": "性格: 活発で遊び好き、猫じゃらしで遊ぶのが好きです。",
        "cat_sugar_bean_name": "猫: シュガービーン",
        "cat_sugar_bean_char": "性格: 温厚で甘えん坊、撫でられるのが好きです。",
        "cafe_details_paws_cat_title": "タイ Paws Cat Cafe の猫たち",
        "cat_coffee_name": "猫: コーヒー",
        "cat_coffee_char": "性格: クールで高慢ですが、心は優しいです。",
        "cat_milk_name": "猫: ミルク",
        "cat_milk_char": "性格: 好奇心旺盛で、新しいものを探求するのが好きです。",
        "back_to_cafes_btn": "カフェリストに戻る",
        "section_donate_title": "寄付で支援",
        "donate_subtitle": "あなたの優しさのひとかけらが、野良猫に温かさと希望をもたらします。",
        "donate_method_alipay": "アリペイ",
        "donate_method_credit_card": "クレジットカード (Visa/Mastercard)",
        "donate_method_apple_pay": "Apple Pay",
        "donate_method_paypal": "PayPal",
        "donate_form_title": "寄付情報を入力",
        "donate_label_name": "寄付者名 (またはニックネーム):",
        "donate_label_location": "場所:",
        "donate_label_amount": "寄付金額 (RMB):",
        "donate_submit_btn": "寄付を確定",
        "donate_recent_donations": "最近の寄付記録",
        "donate_alert_success": "ご寄付ありがとうございます！あなたの優しさがより多くの猫を助けるでしょう。",
        "donate_alert_invalid": "すべての寄付情報を入力し、金額が0より大きいことを確認してください。",
        "section_tracking_title": "支出追跡",
        "tracking_subtitle": "すべての寄付金の使途は透明に開示されます。",
        "tracking_header_date": "支出日",
        "tracking_header_category": "カテゴリ",
        "tracking_header_proof": "支払証明",
        "tracking_header_payer": "支払者",
        "tracking_proof_view": "証明を見る",
        "tracking_proof_none": "証明なし",
        "tracking_add_expense_btn": "新しい支出を追加",
        "tracking_modal_title": "新しい支出記録を追加",
        "tracking_label_date": "支出日:",
        "tracking_label_category": "カテゴリ:",
        "tracking_label_proof": "支払証明 (画像アップロード):",
        "tracking_proof_note": "証明画像をアップロードしてください。",
        "tracking_label_payer": "支払者:",
        "tracking_submit_btn": "送信",
        "tracking_alert_upload_note": "注意: 画像証明はこの例ではローカルプレビュー用です。実際のウェブサイトでは、ファイルをサーバーにアップロードしてアクセス可能なリンクを取得する必要があります。",
        "tracking_alert_success": "支出記録が追加されました！",
        "footer_text": "© 2024 猫の守護者. 無断複写・転載を禁じます。",
        "expense_cat_food": "猫の食料品購入",
        "expense_cat_vaccine": "ワクチン接種費用",
        "payer_aiko": "アイコ",
        "payer_volunteer_a": "ボランティアA"
    }
};
